DELETE http://localhost:3001/api/persons/61431eefb66b7d7444725cbf
###
POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "rest",
    "number": "123213123"
}

### Get one
GET http://localhost:3001/api/persons/5c41c90e84d891c15dfa3431
### Get all
GET http://localhost:3001/api/persons
### Update phone number
PUT http://localhost:3001/api/persons/614480e70b6312373764e2c
content-type: application/json

{
    "number": "1223/456/78"
}

###
GET http://localhost:3001/info