DELETE https://hidden-shore-67603.herokuapp.com/api/persons/6145db34cab202c94510d927
###
POST https://hidden-shore-67603.herokuapp.com/api/persons
content-type: application/json

{
    "name": "rest",
    "number": "123213123"
}

### Get one
GET https://hidden-shore-67603.herokuapp.com/api/persons/6145db20cab202c94510d91d
### Get all
GET https://hidden-shore-67603.herokuapp.com/api/persons
### Update phone number
PUT https://hidden-shore-67603.herokuapp.com/api/persons/6145db20cab202c94510d91d
content-type: application/json

{
    "number": "1223/456/78"
}

###
GET https://hidden-shore-67603.herokuapp.com/info